### ISSUE TITLE
Python cpdf naming ?

### ISSUE THREAD

**Issue by GitHubRulesOK** [py-pdf/cpdf#12]
hmm 
not strictly an issue but a confusion, since cpdf has long time been a Mark (unregistered?) used by coherent command line cpdf tool there is a risk of attempting python wrapper commands that may not be compatible

see https://coherentpdf.com/blog/?s=cpdf especially https://coherentpdf.com/blog/?p=107

**Comment by MartinThoma** [comment]
Thank you for pointing it out. I think @MasterOdin has mentioned it before - I didn't think that others would know / use this as well.

I'm open for other names. It should be pretty short + available on PyPI, though... which makes it tricky.

**Comment by GitHubRulesOK** [comment]
hmm since your running under Py-Pdf why not Py-PdfC [LI] unless a C programmer already beat you to it

**Comment by MartinThoma** [comment]
> why not Py-PdfCLI or PyPDFC

It just feels to long to me. I want to have something shorter

**Comment by GitHubRulesOK** [comment]
well PyDFc is short

**Comment by MartinThoma** [comment]
https://pypi.org/project/pdfly/ - what do you think about that? (I just reserved it so that it's not taken after our discussion :smile: )

**Comment by GitHubRulesOK** [comment]
grin
 pd fly - flies fast (not naturally likely)
 pd fly - in the ointment is more like it

seriously sounds reasonable
